name: Release all project
on:
  push:
    branches:
      - '*'
      - '!master'
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      REF:
        type: string
        required: true
        description: REF
        default: master
      TAG:
        type: string
        required: true
        description: VERSION_TAG
        default: latest
      ENVIRONMENT:
        type: string
        required: true
        description: ENVIRONMENT
        default: DEV

jobs:
  release-all-project:
    uses: the-gymcoder/workflows-catalog/.github/workflows/release-all.yml@init
    permissions:
      contents: read
    with:
      REF: ${{ github.event.inputs.REF }}
      TAG: ${{ github.event.inputs.TAG }}
      ENVIRONMENT: ${{ github.event.inputs.ENVIRONMENT || 'DEV' }}
    secrets: inherit