name: Deploy projects
on:
  workflow_dispatch:
    inputs:
      PROJECT_NAME:
        type: string
        required: true
        description: PROJECT_NAME
        default: dr
      REF:
        description: branch
        type: string
        default: main
        required: true
      ENVIRONMENT:
        type: string
        required: true
        description: ENVIRONMENT
        default: DEV
      TAG:
        type: string
        required: true
        description: VERSION_TAG
        default: latest

jobs:
  deploy-dr-project:
    uses: the-gymcoder/workflows-catalog/.github/workflows/deploy.yml@init
    permissions:
      contents: read
    with:
      REF: ${{ github.event.inputs.REF }}
      ENVIRONMENT: ${{ github.event.inputs.ENVIRONMENT || 'DEV' }}
      TAG: ${{ github.event.inputs.TAG || github.run_number }}
      PROJECT_NAME: ${{ github.event.inputs.PROJECT_NAME || 'dr' }}
    secrets: inherit
