name: Deploy projects
on:
  workflow_dispatch:
    inputs:
      RUNS_ON:
        description: runner tag or runner group
        type: string
        required: true
        default: ubuntu-latest
      REF:
        description: branch
        type: string
        default: main
        required: true
      ENVIRONMENT:
        type: string
        required: true
        description: ENVIRONMENT
        default: dev
      APPS:
        description: "APPS"
        type: string
        required: true
        default: dr thor loki
      CONTAINER_HOST:
        description: "CONTAINER HOST"
        type: string
        required: true
        default: localhost
      TAG:
        type: string
        required: true
        description: VERSION_TAG
        default: latest

jobs:
  deploy-projects:
    uses: the-gymcoder/workflows-catalog/.github/workflows/deploy.yml@init
    permissions:
      contents: read
    with:
      APPS: ${{ github.event.inputs.APPS }}
      RUNS_ON: ${{ github.event.inputs.RUNS_ON || 'ubuntu-latest' }}
      REF: ${{ github.event.inputs.REF }}
      ENVIRONMENT: ${{ github.event.inputs.ENVIRONMENT || 'DEV' }}
      TAG: ${{ github.event.inputs.TAG || github.run_number }}
      CONTAINER_HOST: ${{ github.event.inputs.CONTAINER_HOST }}
    secrets: inherit
