name: Release all project
on:
  push:
    branches:
      - '**'
      - '!master'
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      REF:
        type: string
        required: true
        description: REF
        default: master
      TAG:
        type: string
        required: true
        description: VERSION_TAG
        default: latest
      ENVIRONMENT:
        type: string
        required: true
        description: ENVIRONMENT
        default: DEV

env:
  TEST_ENV_VARIABLE: "Deena"
  ENVIRONMENT: DEV

jobs:
  release-info:
    runs-on: ubuntu-latest
    steps:
      - name: Release info
        run: |
          echo "=======================RELEASE INFO======================="
          echo "REF: ${{ inputs.REF }}"
          echo "TAG: ${{ inputs.TAG }}"
          echo "ENVIRONMENT: ${{ inputs.ENVIRONMENT }}"
          echo "TEST_ENV_VARIABLE: ${{ env.TEST_ENV_VARIABLE }}"
          echo "ENVIRONMENT: ${{ env.ENVIRONMENT }}"
          echo "APPS: ${{ vars.APPS }}"
          echo "=========================================================="

  release-all-project:
    uses: the-gymcoder/workflows-catalog/.github/workflows/release-all.yml@init
    permissions:
      contents: read
    with:
      REF: ${{ github.event.inputs.REF || github.ref_name }}
      TAG: ${{ github.event.inputs.TAG || github.run_number }}
      ENVIRONMENT: ${{ github.event.inputs.ENVIRONMENT || 'DEV' }}
    secrets: inherit
    needs:
      - release-info
