name: Dev Release all project
on:
  push:
    branches:
      - '**'
      - '!master'
      - '!main'
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:
    inputs:
      REF:
        type: string
        required: true
        description: REF
        default: main
      TAG:
        type: string
        required: true
        description: VERSION_TAG
        default: latest

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ENVIRONMENT: dev
jobs:
  import_varaibles:
    runs-on: ubuntu-latest
    environment: DEV
    permissions:
      contents: read
    outputs:
      CONTAINER_HOST: ${{ steps.set-vars.outputs.CONTAINER_HOST }}
      APPS: ${{ steps.set-vars.outputs.APPS }}
      ENVIRONMENT: ${{ steps.set-vars.outputs.ENVIRONMENT }}
      IMAGE_REGISTRY: ${{ steps.set-vars.outputs.IMAGE_REGISTRY }}
      RELEASE_FILE: ${{ steps.set-vars.outputs.RELEASE_FILE }}
      VERSION: ${{ steps.set-vars.outputs.VERSION }}
      PRISTINE: ${{ steps.set-vars.outputs.PRISTINE }}
      DEPLOY: ${{ steps.set-vars.outputs.DEPLOY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: "${{ inputs.REF }}"
      - name: Export environment variables
        run: |
          #!/usr/bin/env bash
          set -euo pipefail
          DIR="$(pwd)"
          yq eval '.variables | to_entries | .[] | "\(.key)=\(.value)"' ${DIR}/environments/${ENVIRONMENT}/variables.yml >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

  release-info:
    runs-on: ubuntu-latest
    environment: DEV
    permissions:
      contents: read
    outputs:
      REF: ${{ steps.set-vars.outputs.REF }}
      TAG: ${{ steps.set-vars.outputs.TAG }}
      ENVIRONMENT: ${{ steps.set-vars.outputs.ENVIRONMENT }}
      APPS: ${{ steps.set-vars.outputs.APPS }}
    steps:
      - name: Variables and Parameter check
        id: set-vars
        run: |
          #!/usr/bin/env bash
          set -euo pipefail
          REF=${{ github.event.inputs.REF || github.head_ref || github.ref_name }}
          TAG=${{ github.event.inputs.TAG || github.run_number }}
          ENVIRONMENT=${{ env.ENVIRONMENT }}
          APPS="${{ vars.APPS }}"
          echo "=======================VARIABLES AND PARAMETER CHECK======================="
          echo "REF=$REF" | tee -a $GITHUB_OUTPUT
          echo "TAG=$TAG" | tee -a $GITHUB_OUTPUT
          echo "ENVIRONMENT=$ENVIRONMENT" | tee -a $GITHUB_OUTPUT
          echo "APPS=$APPS" | tee -a $GITHUB_OUTPUT
          echo "=========================================================="
          echo "cat GITHUB_OUTPUT"
          cat $GITHUB_OUTPUT
          echo "=========================================================="

  release-all-project:
    uses: the-gymcoder/workflows-catalog/.github/workflows/release-all.yml@init
    permissions:
      contents: read
      pull-requests: write
    with:
      REF: ${{ needs.release-info.outputs.REF }}
      TAG: ${{ needs.release-info.outputs.TAG }}
      ENVIRONMENT: ${{ needs.release-info.outputs.ENVIRONMENT }}
      APPS: ${{ needs.release-info.outputs.APPS }}
    secrets: inherit
    needs:
      - release-info