name: Build dr project
on:
  workflow_dispatch:
    inputs:
      RUNS_ON:
        description: runner tag or runner group
        type: string
        required: true
        default: ubuntu-latest
      PROJECT_NAME:
        type: string
        required: true
        description: PROJECT_NAME
        default: dr
      REF:
        type: string
        required: true
        description: REF
        default: main
      TAG:
        type: string
        required: true
        description: VERSION_TAG
        default: latest
      ENVIRONMENT:
        type: string
        required: true
        description: ENVIRONMENT
        default: DEV

jobs:
  build-dr-project:
    uses: the-gymcoder/workflows-catalog/.github/workflows/build-push.yml@init
    permissions:
      contents: read
    with:
      RUNS_ON: ${{ github.event.inputs.RUNS_ON || 'ubuntu-latest' }}
      PROJECT_NAME: ${{ github.event.inputs.PROJECT_NAME || 'dr' }}
      REF: ${{ github.event.inputs.REF || github.head_ref || github.ref_name }}
      TAG: ${{ github.event.inputs.TAG || github.run_number }}
      ENVIRONMENT: ${{ github.event.inputs.ENVIRONMENT || 'DEV' }}
    secrets: inherit