name: Deploy dr project
on:
  push:
    branches:
      - '*'
      - '!master'
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      REF:
        description: "branch"
        type: string
        default: "master"
        required: true

jobs:
  deploy-dr-project:
    uses: the-gymcoder/workflows-catalog/.github/workflows/deploy.yml@init
    permissions:
      contents: read 
    with:
      REF: ${{ github.event.inputs.REF }}
    secrets: inherit
