name: Scan dr project
on:
  workflow_dispatch:
    inputs:
      PROJECT_NAME:
        type: string
        required: true
        description: PROJECT_NAME
        default: dr
      REF:
        description: REF
        type: string
        default: main
        required: true
      ENVIRONMENT:
        type: string
        required: true
        description: ENVIRONMENT
        default: DEV
      TAG:
        type: string
        required: true
        description: IMAGE_TAG
        default: latest

jobs:
  scan-dr-project:
    uses: the-gymcoder/workflows-catalog/.github/workflows/image-scan.yml@init
    permissions:
      contents: read
      pull-requests: write
    with:
      REF: ${{ github.event.inputs.REF || github.head_ref || github.ref_name }}
      ENVIRONMENT: ${{ github.event.inputs.ENVIRONMENT || 'DEV' }}
      TAG: ${{ github.event.inputs.TAG || github.run_number }}
      PROJECT_NAME: ${{ github.event.inputs.PROJECT_NAME || 'dr' }}
    secrets: inherit
