name: Scan dr project
on:
  workflow_dispatch:
    inputs:
      REF:
        description: main
        type: string
        default: main
        required: true
      ENVIRONMENT:
        type: string
        required: true
        description: ENVIRONMENT
        default: DEV
      TAG:
        type: string
        required: true
        description: VERSION_TAG
        default: latest

jobs:
  scan-dr-project:
    uses: the-gymcoder/workflows-catalog/.github/workflows/image-scan.yml@init
    permissions:
      contents: read
      pull-requests: write
    with:
      REF: ${{ github.event.inputs.REF || github.head_ref || github.ref_name }}
      ENVIRONMENT: ${{ github.event.inputs.ENVIRONMENT || 'DEV' }}
      TAG: ${{ github.event.inputs.TAG || github.run_number }}
      APP: "dr"
    secrets: inherit
